2024-12-27 14:24:22.854791+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "\000d\000a    create table [*]order (\000d\000a        id bigint not null,\000d\000a        product_color varchar(255),\000d\000a        product_id bigint,\000d\000a        product_size varchar(255),\000d\000a        quantity integer not null,\000d\000a        primary key (id)\000d\000a    )"; expected "identifier"; SQL statement:

    create table order (
        id bigint not null,
        product_color varchar(255),
        product_id bigint,
        product_size varchar(255),
        quantity integer not null,
        primary key (id)
    ) [42001-232]
2024-12-27 15:25:55.195863+02:00 jdbc[34]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'' (USERS: ""PURCHASE_HISTORY"" BIGINT ARRAY)"; SQL statement:
INSERT INTO "PUBLIC"."USERS"("TYPE","ID","EMAIL","NAME","PASSWORD","USER_IMAGE","ADMIN_LEVEL","PAYMENT_METHOD","PURCHASE_HISTORY","SHIPPING_ADDRESS")VALUES(?,?,?,?,?,?,?,?,?,?) [22018-232]
2024-12-27 15:25:55.197856+02:00 jdbc[34]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'' (USERS: ""PURCHASE_HISTORY"" BIGINT ARRAY)"; SQL statement:
INSERT INTO "PUBLIC"."USERS"("TYPE","ID","EMAIL","NAME","PASSWORD","USER_IMAGE","ADMIN_LEVEL","PAYMENT_METHOD","PURCHASE_HISTORY","SHIPPING_ADDRESS")VALUES(?,?,?,?,?,?,?,?,?,?) [22018-232]
2024-12-27 15:27:12.448839+02:00 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "\000d\000a    create table [*]order (\000d\000a        id bigint not null,\000d\000a        product_color varchar(255),\000d\000a        product_id bigint,\000d\000a        product_size varchar(255),\000d\000a        quantity integer not null,\000d\000a        primary key (id)\000d\000a    )"; expected "identifier"; SQL statement:

    create table order (
        id bigint not null,
        product_color varchar(255),
        product_id bigint,
        product_size varchar(255),
        quantity integer not null,
        primary key (id)
    ) [42001-232]
2024-12-27 15:27:32.960940+02:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'' (USERS: ""PURCHASE_HISTORY"" BIGINT ARRAY)"; SQL statement:
INSERT INTO "PUBLIC"."USERS"("TYPE","ID","EMAIL","NAME","PASSWORD","USER_IMAGE","ADMIN_LEVEL","PAYMENT_METHOD","PURCHASE_HISTORY","SHIPPING_ADDRESS")VALUES(?,?,?,?,?,?,?,?,?,?) [22018-232]
2024-12-27 15:27:32.961936+02:00 jdbc[13]: exception
org.h2.jdbc.JdbcSQLDataException: Data conversion error converting "'' (USERS: ""PURCHASE_HISTORY"" BIGINT ARRAY)"; SQL statement:
INSERT INTO "PUBLIC"."USERS"("TYPE","ID","EMAIL","NAME","PASSWORD","USER_IMAGE","ADMIN_LEVEL","PAYMENT_METHOD","PURCHASE_HISTORY","SHIPPING_ADDRESS")VALUES(?,?,?,?,?,?,?,?,?,?) [22018-232]
2024-12-27 16:55:26.982887+02:00 jdbc[35]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
2024-12-28 04:51:51.244088+02:00 jdbc[35]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:217)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:134)
	at org.h2.Driver.connect(Driver.java:59)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:137)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:360)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:202)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:461)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:724)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:703)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-232]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 16 more
